import { Metadata } from 'next';

export const appMetadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: ['keyword1', 'keyword2', 'keyword3', 'keyword4', 'keyword5', 'keyword6', 'keyword7'],
  manifest: '/manifest.json',
  applicationName: 'Application Name',
  authors: [{ name: 'Your Name', url: 'https://yourwebsite.com' }],

  alternates: {
    canonical: 'https://yourwebsite.com/',
  },

  robots: {
    index: true,
    follow: true,
  },

  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
    other: [
      { rel: 'icon', sizes: '32x32', url: '/favicon-32x32.png' },
      { rel: 'icon', sizes: '16x16', url: '/favicon-16x16.png' },
      { rel: 'mask-icon', url: '/safari-pinned-tab.svg', color: '#5bbad5' },
    ],
  },

  openGraph: {
    title: 'Your Page Title for Social Media',
    description: 'A brief description that will appear when shared on social media.',
    url: 'https://yourwebsite.com/current-page',
    siteName: 'Your Site Name',
    images: [
      {
        url: 'https://yourwebsite.com/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Description of the image',
      },
    ],
    type: 'website',
    locale: 'cs_CZ',
  },

  twitter: {
    card: 'summary_large_image',
    title: 'Your Page Title for Twitter',
    description: 'A brief description that will appear when shared on Twitter.',
    images: [
      {
        url: 'https://yourwebsite.com/twitter-image.jpg',
        alt: 'Description of the image for Twitter',
      },
    ],
  },
};
